### ISSUE TITLE
Disable Self Healing Urls on some routes.

### ISSUE THREAD

**Issue by mrkatz** [motomedialab/laravel-self-healing-urls#1]
I may have something wrong, but I believe that all routes referencing the model we have enabled Self Healing URLs are forced to bind via the full slug. So Route::get('/product/{product:id}/edit', [ProductController::class, 'edit'])->name('product.edit')->can('admin'); Will no longer override this behavior. Is it possible to override depending on route?

**Comment by chrispage1** [comment]
Morning!

Thanks and good point. I've run into this myself and wrote a manual override. In my case it was loading them inside the admin.

I'll add some middleware today that'll temporarily disable the self healing URL behaviour 👍🏻

**Comment by chrispage1** [comment]
I've added some additional tests and `Motomedialab\LaravelSelfHealingUrls\Middleware\DisableSelfHealingUrls::class` middleware. Its important to note this will **need** to be called before the web middleware initialisation 👍

**Comment by chrispage1** [comment]
PR #2 also :)

**Comment by mrkatz** [comment]
Nice work thank you. Much simpler solution then what I had been working on.
